export const USER_LOGGED_IN      = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT     = 'USER_LOGGED_OUT';
export const BOOKS_FETCHED       = 'BOOKS_FETCHED';
export const BOOK_CREATED        = 'BOOK_CREATED';
export const LOCALE_SET          = 'LOCALE_SET';

export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST';
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE';
export const FETCH_CURRENT_USER_REQUEST = 'FETCH_CURRENT_USER_REQUEST';
export const FETCH_CURRENT_USER_SUCCES  = 'FETCH_CURRENT_USER_SUCCES';
// DREAMS
export const DREAM_CREATED  = 'DREAM_CREATED';
export const CREATE_DREAM_REQUEST = 'CREATE_DREAM_REQUEST';
export const DREAMS_FETCHED = 'DREAMS_FETCHED';
export const FETCH_DREAMS_REQUEST_SUCCES = 'FETCH_DREAMS_REQUEST_SUCCES';