export const USER_LOGGED_IN      = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT     = 'USER_LOGGED_OUT';
export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST';
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE';
export const FETCH_CURRENT_USER_REQUEST = 'FETCH_CURRENT_USER_REQUEST';
export const FETCH_CURRENT_USER_SUCCES  = 'FETCH_CURRENT_USER_SUCCES';
// DREAMS
export const DREAM_CREATED  = 'DREAM_CREATED';
export const CREATE_DREAM_REQUEST = 'CREATE_DREAM_REQUEST';
export const DREAMS_FETCHED = 'DREAMS_FETCHED';
export const FETCH_DREAMS_REQUEST_SUCCES = 'FETCH_DREAMS_REQUEST_SUCCES';
export const CREATE_DREAM_FAILURE = 'CREATE_DREAM_FAILURE';
export const DELETE_DREAM_REQUEST = 'DELETE_DREAM_REQUEST';
export const DELETE_DREAM_SUCCES  = 'DELETE_DREAM_SUCCES';
export const FETCH_ONE_DREAM_REQUEST = 'FETCH_ONE_DREAM_REQUEST';
export const FETCH_ONE_DREAM_REQUEST_SUCCES = 'FETCH_ONE_DREAM_REQUEST_SUCCES';